version: 2,
exclude_patterns:
- ".github/"
- ".idea/"
- "dist/"
- "docs/"
- "**/tools/"
- "**/vendors/"
- "examples/"
- "documentation/"
- "**/test/"
- "**/__test__/"
- "**/*.d.ts"
- "**/*.test.js"
- "**/*.test.ts"
- "**/*.test.tsx"
- "**/*.e2e.js"