version: "2"
exclude_patterns:
- ".github/"
- "**/dist/"
- "**/tools/"
- "**/vendors/"
- "examples/"
- "documentation/"
- "**/test/"
- "**/__test__/"
- "**/*.test.js"
- "**/*.test.ts"
- "**/*.test.tsx"
- "**/e2e/"
- "**/*.d.ts"