const ACTIONS = {
  SHOW_NAV: 'SHOW_NAV',
  UPDATE_LOADING_STAGE: 'UPDATE_LOADING_STAGE',
  SHOW_TERMINAL: 'SHOW_TERMINAL',
  SHOW_DISPLAY_MODE: 'SHOW_DISPLAY_MODE',
  SHOW_DISPLAY_COLOR: 'SHOW_DISPLAY_COLOR',
  CHANGE_THEME: 'CHANGE_THEME',
};

export default ACTIONS;
