const ACTIONS = {
  SHOW_NAV: 'SHOW_NAV',
  SEND_INFO: 'SEND_INFO',
  UPDATE_LOADING_STAGE: 'UPDATE_LOADING_STAGE',
  SHOW_TERMINAL: 'SHOW_TERMINAL',
  SHOW_DISPLAY_MODE: 'SHOW_DISPLAY_MODE',
  SHOW_DISPLAY_COLOR: 'SHOW_DISPLAY_COLOR',
  SAVE_COLORERS: 'SAVE_COLORERS',
  SAVE_MODES: 'SAVE_MODES',
  SAVE_VIEWER: 'SAVE_VIEWER',
  CHANGE_THEME: 'CHANGE_THEME',
};

export default ACTIONS;
